### ISSUE TITLE
Port to Fitbit OS?

### ISSUE THREAD

**Issue by benjamin-antupit** [freakified/TimeStylePebble#110]
Hello!
I was wondering if anyone working on this project has plans to port this (amazing) watchface to Fitbit OS (for Fitbit Iconic). I'm thinking about getting an Iconic now that Pebble services are shutting down in 6 months, but I'll hold onto my pebble as long as this watchface is on it!

**Comment by tilden** [comment]
That is actually the only thing I am actively working on at this point! Stay tuned for exciting updates on that front.

**Comment by foxt** [comment]
I was ctually planning on this, then I realized I do not know the FitBit API

**Comment by IAMIronmanSam** [comment]
Any update on this? i found a similar watch face https://github.com/TranquilMarmot/StyleTime

**Comment by tilden** [comment]
Oh! Not a fan of that one, some really strange design decisions there.

That said, I did start on one for Ionic, but I never finished it. I'll dig up the source code and post it tonight!

**Comment by tilden** [comment]
I've pushed the latest code to https://github.com/freakified/TimeStyleFitbit

If anyone would like to take over development, I'd be happy to collaborate! Unfortunately, I don't really have time to work on it anymore.

It currently runs on Ionic, but has the following limitations:

- Config page doesn't actually change watchface colors
- Widgets cannot be changed or reordered
- No weather support
- No Versa support

Here are some of my mockups for the design:

### Ionic:
![image](https://user-images.githubusercontent.com/466332/59403398-5341c080-8d57-11e9-8355-0da1842a5f8e.png)
![image](https://user-images.githubusercontent.com/466332/59403472-8e43f400-8d57-11e9-8e20-b002c6f76045.png)


### Versa:
![image](https://user-images.githubusercontent.com/466332/59403421-63f23680-8d57-11e9-83ee-9f9e30ccba94.png)

**Comment by derekwilson** [comment]
Maybe have a look at this watchface - it should work on all versions of Fitbit Ionic and Versa?

https://gallery.fitbit.com/details/dfe5fccd-01e5-4979-a5ad-070673df12dd

I think it does have its moments - granted I am bias :-)

**Comment by benjamin-antupit** [comment]
Very nice. Thanks for sharing @derekwilson.
