### ISSUE TITLE
Top Bar Position - Timeline Quick View Oddity - Solid Bar Appears at top of screen

### ISSUE THREAD

**Issue by brendenglynn** [freakified/TimeStylePebble#111]
When the Top Bar Position is set and a Timeline Quick View appears, a solid bar is shown on the top of the screen.

This behavior does not present when the Bottom Bar position is set.

See linked photos for reference:

https://imgur.com/a/u5akN

I use the bottom bar position daily, so no impact on my usage. But wanted to bring it to light!

Amazing watchface. My go-to on my PTR and now my P2HR!

**Comment by plarus** [comment]
@freakified: This issue was wrongly opened here.
Was opened here instead: [TimeStyleBBPebble#11](https://github.com/plarus/TimeStyleBBPebble/issues/11)

Can be closed !
