### ISSUE TITLE
How to compile for Aplite?

### ISSUE THREAD

**Issue by ghost** [freakified/TimeStylePebble#119]
Hello, it seems like the store version works perfectly on Aplite but it seems like this source code can be compiled but can't be run on Aplite. Is there a way to compile and make this watchface work on older models?

**Comment by tilden** [comment]
Once I switched the font rendering to use that FCTX library, the memory usage was always too high for Aplite, so the Aplite version on the store is actually a much older build, that I manually bundled into the PBW.

To build that version, try reverting to one of the commits around 5701ee909491c15f868a3fc7cd89ca84db4ba1d0 -- the version from back then should compile for Aplite without any issues.
