### ISSUE TITLE
Week number option in sidebar

### ISSUE THREAD

**Issue by tilden** [freakified/TimeStylePebble#19]
If issue #16 is completed, there would be new possibilities for what could be displayed in the sidebar.

I've had a request for a current week number to be one such option.

**Comment by wicol** [comment]
I would love to see this. I keep switching between this and "TIMEWATCH" which has a nice icon for precisely this. Check it out for inspiration :)

**Comment by tilden** [comment]
It's actually coming in the next version! :sunglasses: 

Question for you: in your country, how do you expect to see week numbers shown? Just a number? The local word for "week" and the number? Something else?

**Comment by wicol** [comment]
Awesome! Personally I dont mind english names of days/weeks/months as long as I can get something like ISO 8601. But W38 is usually written as V38 in swedish since Week = Vecka. Looking forward to next release!

**Comment by tilden** [comment]
Completed in fb21b3d4e97f0fd3eb2effa808ef1dc03be96ec1
