### ISSUE TITLE
Bold font option for the time

### ISSUE THREAD

**Issue by Leo-chaos** [freakified/TimeStylePebble#23]
Option for different font thickness for the time, I prefer avenir by far, but it seems a bit thin, compared to the space it has

**Comment by tilden** [comment]
I've also gotten a request for the Magento font as well

**Comment by tilden** [comment]
After consideration, I've decided that the new font will be Avenir Bold, which should address the concerns about the readability of the default weight.

**Comment by tilden** [comment]
Completed
