### ISSUE TITLE
Enter animation for sidebar

### ISSUE THREAD

**Issue by rosenpin** [freakified/TimeStylePebble#24]
It would be really neat if there could be an entering animation for the sidebar like this one:
![Pebble Gif](http://i.imgur.com/6zHRzr3.gif)

**Comment by tilden** [comment]
How would you envision the animations looking, specifically?

The animations on the Timeline itself are always traveling up or down, based on the direction in the timeline that you're going. For the watchface, you're in the present, so we can't really say up or down. What do you think?

**Comment by rosenpin** [comment]
I meant for only entering animation, so when the watchface is loaded the taskbar will make an animation from bottom to top kind of like the weather icon in the gif

**Comment by tilden** [comment]
Especially now that Pebble has change the watchface entry animation so that it just slides in, I don't think this is needed any longer
