### ISSUE TITLE
Advanced minute/hour style

### ISSUE THREAD

**Issue by alaintxu** [freakified/TimeStylePebble#27]
Hi!
There is a Watchface that I like called "Moment". It is very stylish, but too simple. There are 2 interesting features that I would like to see implemented in this watch:

1.- Different size/colour in minutes/hours: The hours have a bold font while the minutes don't. And the minutes have lighter colours too.
2.- Animation when time changes: there are animations when any digit changes.

I think that those 2 features would make this Watchface more "stylish".

Thank you for your work!

**Comment by tilden** [comment]
The latest release allows for bold/non-bold hours/minutes, which I think solves this issue
