### ISSUE TITLE
Random weather

### ISSUE THREAD

**Issue by nymitr** [freakified/TimeStylePebble#32]
Recently started to show a random weather.
I copied a request from the source code and try it few times in browser. It returns the weather on different days: 13 Nov, 11 Nov, 12 Nov, sometimes 16 Nov(today).

**Comment by tilden** [comment]
Yes, I've verified this on my computer and watch. It appears to be an issue with Yahoo weather itself. Interestingly, it appears that for users in certain geographic locations it occurs more frequently, or sometimes not at all.

I'm hoping they fix it, but if they don't, I may have no choice but to switch back to OpenWeatherMap.

**Comment by tilden** [comment]
Looks like Yahoo fixed the issue. Closing for now.
