### ISSUE TITLE
Forecast.io API support

### ISSUE THREAD

**Issue by singingtelegram** [freakified/TimeStylePebble#38]
It will be great if someone can add support for [The Dark Sky Forecast API](https://developer.forecast.io/docs/v2). API calls are limited but we can use our own API keys.

**Comment by tilden** [comment]
If someone is interested in adding this I would definitely accept the pull request.

**Comment by singingtelegram** [comment]
I'll have a try (:

**Comment by Miaourt** [comment]
I want to try too :)

**Comment by bumper314** [comment]
Just wanted to see if anyone has made progress on this before I spec out this job for a contractor.

**Comment by tilden** [comment]
I've made some progress on my local branch, I'm hoping it have it released this week.

**Comment by tilden** [comment]
Weather underground support was added in version 6.0, which I believe should cover the underlying issue (that OpenWeatherMap data is terrible.) If there is significant enough demand, this issue could be reopened.
