### ISSUE TITLE
Distribute the app trought Github's release ? :o

### ISSUE THREAD

**Issue by Miaourt** [freakified/TimeStylePebble#42]
For those who don't use the "official" Pebble NSA-like app, could be possible to get the .pbw (watchface) trought Github release page ? ^^

**Comment by tilden** [comment]
You can download the PBW and sideload it from the "Download PBW" link at the bottom of this page:

https://apps.getpebble.com/en_US/application/55a5c024f4510f794c000071?dev_settings=true&section=watchfaces

**Comment by Miaourt** [comment]
Oh, sorry for disturbing, newcomer here ^^"
