### ISSUE TITLE
Settings menu hangs

### ISSUE THREAD

**Issue by zach-is-my-name** [freakified/TimeStylePebble#64]
App 2.6.9
Watch 2.9.1 

Can't access settings menu, spins continuously

**Comment by tilden** [comment]
Can't replicate; it's loading fine for me on Android app 3.10.1, Watch 3.10.1. I'm closing for now unless there are more reports of this issue.

It _should_ work on 2.9.1 still, but that version is officially deprecated so I no longer test on it.

**Comment by zach-is-my-name** [comment]
It's a pebble issue. Ok after multiple resets/reconnects. You're loaded now thanks.
