### ISSUE TITLE
Weather does not update

### ISSUE THREAD

**Issue by IguanaBen** [freakified/TimeStylePebble#68]
I find that the weather does not update unless I exit the watchface (go to app, timeline, etc). I think I've traced the problem to the the following starting at 163 in main.c:

``` c
// every 30 minutes, request new weather data
  if(!globalSettings.disableWeather) {
    if(tick_time->tm_min == weatherRefreshMinute && tick_time->tm_sec == weatherRefreshSecond) {
      messaging_requestNewWeatherData();
    }
  }
```

In most circumstances the tick_time updates once a minute and since the weatherRefreshSecond is a random number, the 3rd line never evaluates to true. I think you want something like:

``` c
// every 60 minutes, request new weather data
  if(!globalSettings.disableWeather) {
    if(tick_time->tm_min == weatherRefreshMinute && (!globalSettings.updateScreenEverySecond || tick_time->tm_sec == weatherRefreshSecond) {
      messaging_requestNewWeatherData();
    }
  }
```

This will update every 60 minutes (not 30 as the comment says) but only check the seconds if the screen (and thus tick) is updating every second. 

Please let me know if you'd like a pull request.

**Comment by tilden** [comment]
Thanks for pointing this out! In fact, it seems to me that the entire "weatherRefreshSecond" is mostly pointless, since as you point out it only applies when the seconds mode was enabled. I've just dropped it entirely. Thanks!
