### ISSUE TITLE
Battery indicator doesn't match settings tile at 0%

### ISSUE THREAD

**Issue by PonyOny** [freakified/TimeStylePebble#69]
When battery is below 10% it will display 0% battery, and if you have a look in the menu settings it displays 5%.
![image1](https://cloud.githubusercontent.com/assets/17080292/14462267/7cc02c92-00c6-11e6-9ea7-a3155e6f5664.JPG)
![image2](https://cloud.githubusercontent.com/assets/17080292/14462271/82ccc104-00c6-11e6-9bef-7f17228ccafe.JPG)

**Comment by tilden** [comment]
So I directly display what the Pebble is providing via its [Battery State API](https://developer.pebble.com/docs/c/Foundation/Event_Service/BatteryStateService/#BatteryChargeState), which apparently doesn't match what their own settings page shows. I could hardcode it to show "0" as "5", but that seems kind of hack-ish.

**Comment by tilden** [comment]
OK, just discussed this with some pebble people and apparently this is an actual quirk in the API. I'll consider adding the modification.

**Comment by tilden** [comment]
Fixed in version 6.0
