### ISSUE TITLE
Add sleep mood / power saving mode

### ISSUE THREAD

**Issue by livekn** [freakified/TimeStylePebble#70]
It can be automatic activated by time. When it's enabled, no hourly vibrate (even if it was turned on), no weather update check, no seconds, ignore bluetooth state.

**Comment by Coollision** [comment]
I'd love to see this function happen as wel! This  way i don't have to turn of hourly vibrations of at night of change watchface because somtimes they wake me up.....

**Comment by tilden** [comment]
Yes, there have been several requests for some kind of quiet time. I'm hoping that Pebble releases a Quiet Time API or just disables vibrations for 3rd party apps during quiet time. Their current implementation (notifications only) doesn't make sense, IMO.

**Comment by mvoropaiev** [comment]
Would like to see such option as well, there are some other watchfaces allowing to set the start and end times for quiet time, but I really like this one :smile: So with this approach you at least can set it to match scheduled quiet time on pebble, which is kinda okay for night times.

**Comment by tilden** [comment]
Pebble has finally added a quiet time API, and as of version 6.11 the watchface respects those settings!

**Comment by mvoropaiev** [comment]
@tilden awesome news, thanks!
