### ISSUE TITLE
Embed WeatherUnderground API

### ISSUE THREAD

**Issue by tuz83** [freakified/TimeStylePebble#73]
Hi!
I've got a wish for my favorite watchface …

As WeatherUnderground provides the most accurate weather data for my location (Vienna, Austria) I would wish for the implementation to choose WeatherUnderground as the data provider - with my own API Key.

I know that there's a already a post asking for "#38 - Forecast.io API support" 
Perhaps it's possible to integrate different weather services and let the user choose in the options (like other watchfaces)

regards, Tom

**Comment by tilden** [comment]
Completed as of version 6.0

**Comment by bumper314** [comment]
Thank you Dan.  Can I donate to support your efforts?
