### ISSUE TITLE
Add combined date/week number

### ISSUE THREAD

**Issue by machineboycom** [freakified/TimeStylePebble#74]
It would be nice to have a possibility to add the current date (maybe without month or day?) to the week number complication.

Mockup: http://imgur.com/lueWhad

![image](https://cloud.githubusercontent.com/assets/12409784/15739993/2646e472-28b3-11e6-8245-5a9e4fb76ef5.png)

**Comment by tilden** [comment]
It's interesting, but kind of a niche case. A more general approach would be to split out components of the date element into separate parts.

In addition, I suspect that "W23" would have trouble fitting if displayed using the canonical Pebble fonts.

**Comment by dagbdagb** [comment]
Side note:
Also note that one should not trust week numbers  across geographical locations. 
See https://www.msoutlook.info/question/week-numbers-calendar-wrong.

**Comment by tilden** [comment]
@dagbdagb: I'm just using the built-in week number function, conveniently making that not my problem! 😄

**Comment by tilden** [comment]
Closing for now; I believe a more general approach to widget compaction would be preferable to just implementing special combined widgets.
