### ISSUE TITLE
Weather data not updated (regular) using weather underground

### ISSUE THREAD

**Issue by MariusRumpf** [freakified/TimeStylePebble#77]
I have set Location to Automatic (GPS), Units to Celsius, Data Source to Weather Underground and entered my API key. Looking at the api analytics there where very few calls to the api. Maybe only those when submitting the watchface settings. When setting the Location to Manual (Hamburg, Germany) I have no updates at all, not even when submitting the settings to the clock.

Here are the api usage metrics:
![API usage metrics](https://cloud.githubusercontent.com/assets/2364426/16080347/a304797a-3308-11e6-8ce7-b15aef27e1b2.jpg)

Might be related to #76.

**Comment by tilden** [comment]
Strange indeed, I'll have to look into this. Are you using "forecast", "current conditions", or both?

**Comment by MariusRumpf** [comment]
Weather: Current only, selected in top Complications.

**Comment by tilden** [comment]
One more question: is the exact location string "Hamburg, Germany"?

**Comment by MariusRumpf** [comment]
No sorry, it is `Hamburg, Deutschland` as selected from the Google Autocomplete Suggestion.

**Comment by MariusRumpf** [comment]
If you have an idea how I might help you with debugging feel free to tell me.

**Comment by stevier5000** [comment]
Having a similar (same?) issue. I just signed up for a weatherunderground API key yesterday, and only saw 2 API calls in the last 12 hours. For instance, right now its 8:30am local time, and my current weather still shows a "moon" icon, and "..." for the forecast. Location string is "Huntington Beach, CA, USA" for me. I have current weather on the top, forecast in the middle.

**Comment by MariusRumpf** [comment]
Debugged it just now and received the following errors

```
[19:46:08] javascript> TimeStyle:652 Get weather function called! DisableWeather is 'no'
[19:46:08] javascript> TimeStyle:1038 http://api.wunderground.com/api/API_KEY/forecast/q/Hamburg%2C%20Deutschland.json
[19:46:08] javascript> TimeStyle:1007 Uncaught TypeError: Cannot read property 'temp_c' of undefined
[19:46:08] javascript> TimeStyle:1045 Uncaught TypeError: Cannot read property 'simpleforecast' of undefined
```

The api response is:

``` json
{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "forecast": 1
  }
        , "results": [
        {
        "name": "Hamburg",
        "city": "Hamburg",
        "state": "",
        "country": "DL",
        "country_iso3166":"DE",
        "country_name":"Germany",
        "zmw": "00000.3.10147",
        "l": "/q/zmw:00000.3.10147"
        }
        ,
        {
        "name": "Hamburg",
        "city": "Hamburg",
        "state": "",
        "country": "DL",
        "country_iso3166":"DE",
        "country_name":"Germany",
        "zmw": "00000.5.10147",
        "l": "/q/zmw:00000.5.10147"
        }
        ,
        {
        "name": "Hamburg",
        "city": "Hamburg",
        "state": "",
        "country": "DL",
        "country_iso3166":"DE",
        "country_name":"Germany",
        "zmw": "00000.4.10147",
        "l": "/q/zmw:00000.4.10147"
        }
        ,
        {
        "name": "Hamburg",
        "city": "Hamburg",
        "state": "",
        "country": "DL",
        "country_iso3166":"DE",
        "country_name":"Germany",
        "zmw": "00000.3.10147",
        "l": "/q/zmw:00000.3.10147"
        }
        ]
    }
}
```

**Comment by stevier5000** [comment]
Looks like maybe the autocomplete locations are leading to the wrong query. Based on Marius' comment above, its translating the location into a URI. Presumably, mine would have been:
http://api.wunderground.com/api/APIKEY/forecast/q/Huntington%20Beach%2C%20CA%2C%20USA.json
which doesn't work - I get json back for every "Huntington" across the US. This is the proper url:
http://api.wunderground.com/api/APIKEY/conditions/q/CA/Huntington_Beach.json

I tried entering "CA/Huntington_Beach" in the watchface settings, but doesn't appear to be working. Not sure how to debug and dig in further.

**Comment by tilden** [comment]
Thanks for looking at the logs! Yes, it appears that the issue is that Weather Underground is having trouble disambiguating certain locations. I'll have to see if I can find a way to make it more decisive.

**Comment by MariusRumpf** [comment]
As a quick fix I put my geo location in and did not choose a location from the auto suggestion.
A good fix might be to save the geo location you get from the google suggestion selection and send that to the api. Does this work with open weather?

**Comment by tilden** [comment]
I just pushed out a release with a fix. The approach I used ended up being essentially what you proposed; saving the geo location from Google. It's also able to fall back to the original method so that people with currently working weather won't suddenly find it broken, and users in China should still be able to input location strings.

**Comment by MariusRumpf** [comment]
Thanks a lot for the bugfix and the great watchface!
