### ISSUE TITLE
Make battery indicator be hidden until battery below X%

### ISSUE THREAD

**Issue by dagbdagb** [freakified/TimeStylePebble#82]
Using all three complications may make the sidebar a little crowded. I suggest making the battery indicator be (optionally) hidden until battery drops below a user specified percentage.

**Comment by tilden** [comment]
This feature already exists, albeit without the configurable percentage. 

After the battery dips below 10%, the battery indicator appears. The threshold could be configurable, but I haven't seen a huge demand for that as of yet. Closing for now, unless someone really wants to contribute the feature.

**Comment by dagbdagb** [comment]
Odd. My battery indicator is visible at all times?

**Comment by tilden** [comment]
If you leave off the battery indicator altogether, but leave an empty slot, it will automatically appear in that slot. It follows the following rules:
1. If there is an empty slot, the battery indicator goes there. If not...
2. If there is a slot based on weather, it replaces that. If not...
3. It just takes the middle slot

**Comment by dagbdagb** [comment]
Tusen takk!   :-)
