### ISSUE TITLE
Use ACTION_BAR_WIDTH instead of "#define SIDEBAR_WIDTH 30" in sidebar.c

### ISSUE THREAD

**Issue by jorsmm** [freakified/TimeStylePebble#91]
You can use `ACTION_BAR_WIDTH` instead of "`#define SIDEBAR_WIDTH 30`" in **sidebar.c**.
I think It has different size in Time vs Time 2 (30 vs 34).
Thanks!!

**Comment by tilden** [comment]
Huh, I never noticed that `ACTION_BAR_WIDTH` was the same width as the timeline. This would be much more elegant than hardcoding 30/34 depending on platform. Thanks for the tip!
