### ISSUE TITLE
Heartrate is not displayed when bluetooth is off

### ISSUE THREAD

**Issue by adobi** [freakified/TimeStylePebble#93]

**Comment by tilden** [comment]
Is the heart rate widget in the middle slot? If so, try putting it in the top slot -- it's possible that the middle slot is just being replaced by the disconnect indication.

**Comment by adobi** [comment]
Okey. So when the watch and the phone are not connected, an indicator is displayed always?

**Comment by tilden** [comment]
Correct. There is currently an issue for an option to hide that icon, issue #65

**Comment by tilden** [comment]
Closing as a duplicate of issue #65
