### ISSUE TITLE
Version in pebble appstore is broken for diorite, building from source works

### ISSUE THREAD

**Issue by ashimokawa** [freakified/TimeStylePebble#96]
When installing the pbw from the appstore, I cannot use the heart rate or health features. When configuring the watchface to show these, there is just an empty space.

When building the source myself and "sideloading" the pbw, it works however as expected.

**Comment by tilden** [comment]
Hm, working for me. for me -- Pebble 2 w/ firmware 4.3, appstore version, Android app.

**Comment by ashimokawa** [comment]
@tilden 
Weird, I installed the appstore version again and both icons vanished again (without reconfiguring), then installed the self-built version again and they reappeared (also without reconfiguring)

But since I use https://github.com/Freeyourgadget/Gadgetbridge and not the official app, it *might* be my own weird bug, even though I don't have any idea how this can happen.

Feel free to close this without any attention, I do not expect anyone to support Gadgetbridge. ;)

**Comment by tilden** [comment]
Yeah, I haven't gotten any other reports of this, and I'm guessing I would be getting a pretty large volume of emails if P2 users couldn't get HRM or steps, so perhaps it's an issue with Gadgetbridge interacting weirdly with the health API.

Closing for now.
